KangSooHan/SSD_project_Team_D

ssd/normal_ssd.py, tests/test_ssd_read.py
- NormalSSD의 read 테스트 추가
- NormalSSD의 read 기능 구현
---
---
- 추후 write 구현이 완료되면 병합 및 리팩토링 예정
=> [feat] NormalSSD의 read 기능 구현 및 테스트 추가

shell/commands/testscenario1.py, ssd/abstract_ssd.py, tests/test_testscenario.py
- 사용자 요청에 따라 `TestScenario1`을 수행하는 shell command 구현
- 추후 적용될 Command Pattern/Duck typing 적용을 위해 실행 함수명을 `execute`로 정의
- 구현 기능 검증을 위한 unit test 추가
- 개발 사양서에 정의된 아래 시나리오를 수행  
- 개발 사양서에 제시된 `read_compare` 기능은 메서드로 구현하여, 결과에 대해 `bool True/False` 값을 리턴
- `read_comapare` 결과에 따라 `execute` 메서드는 `PASS` or `FAIL` 값을 리턴 
- 오전 스탠드 미팅에서 논의 된 `AbstractSSD.read` 메서드에 대한 리턴값 타입 힌트 수정
---
---
- #1 
---
- PR header, commit header 모두 규칙에 따라 feat, refactor를 사용하였습니다.
- branch 규칙은 팀 규칙인 `feature/` prefix를 적용하고, shell 개발 담당자 규칙인 `feature/shell_{command name}`을 적용하였습니다. 
- unit test 실행 결과
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - …
=> [feat] 테스트 시나리오 1번 기능을 위한 `TestScenario1` 클래스 구현

tests/test_validator.py, validator.py
[Feature] Validator 검증기 구현
<details>
- `feat`: Validator Class 추가했습니다. 검증기를 통해 SSD Shell 에 들어오는 String Command Input의 유효성을 검사합니다.
- `fix`: 버그 수정
- `test`: 
test/test_validator.py 에 구현했습니다.
</details>
---
Validator를 구현했습니다. 주요 동작은 아래와 같습니다:
- 대소문자 구분
- 공백 문자 처리
- 입력값이 다음과 같을 경우 처리:
- `W` → `True`, `ADDR(0~99)`, `Value(0x00000000 ~ 0xFFFFFFFF)` (정수형)
- `R` → `True`, `ADDR(0~99)`, `None`
- 그 외 → `False` 반환
---
---
---
=> [Feature] Validator 검증기 구현

shell/commands/help_command.py, tests/test_shell_help_command.py
<details>
- `fix`: 버그 수정
</details>
---
- shell의 help command 기능 구현했습니다. 
- 별도 ssd 객체 사용이 필요없어 mock은 활용하지 않고 sys.stdout 을 이용하여 print 값만 검증하였습니다.
---
---
---
=> [feat] shell help 기능 구현

shell/commands/read_command.py, tests/test_shell_read.py
<details>
- `fix`: 버그 수정
</details>
---
- SHELL  read command 기능 구현했습니다.
- write 기능과 마찬가지로, validator에서 범위 검증 예정이므로, 테스트로 lba 범위 검증만 진행하였습니다. 
---
---
---
=> [feat] shell read 기능 구현

shell/commands/exit_command.py, tests/test_shell_exit_command.py
<details>
- `fix`: 버그 수정
</details>
---
- shell exit command 기능 구현하였습니다.
- sys.exit(0) 수행 동작 및 검증하였습니다.
---
---
---
=> [feat] shell exit 기능 구현

shell/normal_ssd_driver.py, tests/test_shell_normal_ssd_driver.py
<details>
- `fix`: 버그 수정
</details>
---
- shell에서 system call 방식으로 사용할 normal_ssd_driver 를 구현했습니다.
- normal_ssd_driver는 ssd.normal_ssd의 NormalSSD 클래스를 참조하여, NAND_FILE과 OUTPUT_FILE 경로를 가져옵니다.
- 이후 subprocess.run 함수를통해 ssd.py 파일을 실행하여 read/write 기능을 실행합니다.
- read 시 혹시모를 상황을 대비하여  sleep 0.1초를 줬습니다. 
---
---
---
=> [feat] shell ssd driver 기능 개발

ssd.py, tests/test_ssd.py, validator.py
[feat] SSD Validator 추가 및 실행 확인
<details>
- `feat`: [feat] SSD Validator 추가 및 실행 확인
- `fix`: LBA 검사를 int(lba, 16) 으로 진행하던 버그를 수정했습니다.
</details>
---
- 구현된 ssd.py 에 Validator를 추가했습니다.
- pytest를 기반으로 ssd_main과 validate_main을 비교하고 일치함을 검증했습니다.
- 마지막으로 validate_main을 ssd_main으로 수정했습니다.
---
---
- [관련된 이슈 번호 또는 링크 (예: `#2`)](https://github.com/KangSooHan/SSD_project_Team_D/pull/20)
---
=> [feat] SSD Validator 추가 및 실행 확인

shell.py, ssd.py, tests/test_ssd.py, tests/test_validator.py, validator.py
[feat] Shell Validator 개발 & [fix] Validator 버그 Fix
<details>
- `feat`: Shell Validator를 개발했습니다
- `fix`: w r write read 등등 다양한 케이스를 validate 할 때 오류가 있어 수정했습니다.
- `refactor`: Validator 상속 및 ShellValidator SSDValidator 구현
- `test`: test_ssd test_validator
</details>
---
ShellValidator 클래스 내부 명령어별 유효성 검사 로직을 통합 및 개선하였습니다.
write, read, fullwrite, help, exit, fullread 명령에 대해 인자 개수 및 타입(hex, int) 기반의 세부 유효성 검사를 구현하였습니다.
기존 단순 길이 검증 방식에서 → 실제 인자의 타입까지 검증하는 방식으로 고도화하였습니다.
그 외 명령어 축약형(w, r)도 동일하게 처리되도록 반영하였습니다.
---
---
---
=> [feat] Shell Validator 개발 & [fix] Validator 버그 Fix

shell_core/commands/full_write_command.py, shell_core/commands/write_command.py, shell_core/normal_ssd_driver.py, tests/test_shell.py
<details>
- `fix`: 버그 수정
</details>
---
- SSD 클래스 구조 설계 및 구현
- 테스트 스크립트 실행 오류 수정
---
---
---
=> [fix] Fix write test

shell_core/commands/full_write_command.py
<details>
- `fix`: 버그 수정
</details>
---
- fullwrite 시 print([]) 제거
---
---
---
=> [fix] fullwirte 수정

shell_core/logger.py, tests/test_logger.py
- logger.py 변경 : log 파일이 테스트로 인해 단시간에 생길시, _1, _2 ... 등등 추가
- 테스트 추가
로거 테스트 파일 추가, 로그파일에_쓰기_테스트, 여러개_쓰기_테스트, 롤링테스트, zip으로_바꾸는지_체크
---
=> [feat] Logger 변경 및 Test 추가

shell_core/logger.py
기존 포맷이 요구사항과 맞지 않아 아래 요구사항에 맞게 수정했습니다.
=> [style] 로그 파일 시간 포맷 수정

ssd_core/normal_ssd.py, tests/test_ssd_io.py
<details>
- `fix`: 버그 수정
</details>
---
- ssd erase 구현
- ssd erase test 구현
---
---
---
=> [feat] normal_ssd에 erase 기능 추가 및 test case 추가

ssd.py, tests/test_ssd.py, validator.py
<details>
- `fix`: 버그 수정
</details>
---
- erase 분기문 추가 
- validator의 dataclass에 새로운 변수 추가
- 관련 test code 추가
---
---
---
=> [feature] ssd 및 validator 모듈에 erase 기능 및 테스트 코드 추가

command_core/command_factory.py, command_core/shell_commands/flush_command.py, shell_core/normal_ssd_driver.py, ssd_core/abstract_ssd_driver.py, validator.py
- validator 항목 추가
- command 항목 추가
- ssd_driver 에 flush 추가
---
=> [feat] Flush 기능 추가

ssd_core/normal_ssd.py
-  flush 실행 시 기존 write 값 변경이 안되던 문제 수정
- overwrite 플래그가 self 로 잡혀 있어서, 한번 True가 되면 계속 True 상태로 유지되는 문제 제거
---
---
---
=> [feat] Flush - flush 실행 시 기존 write 값 변경이 안되던 문제 수정

ssd_core/simple_buffer_optimizer.py, tests/test_simple_buffer_optimizer.py
<details>
- `fix`: 버그 수정
</details>
---
- **SimpleBufferOptimizer** 클래스 구현  
- 중복 쓰기 제거, 쓰기 전 이레이즈 무효화, 이레이즈 구간 병합 로직 구현  
- `calculate` → `_optimize_once` → `_drop_redundant_writes` → `_drop_duplicate_writes` → `_merge_erase_commands` 흐름 구성  
- 상수 `MAX_ERASE_SIZE = 10`로 이레이즈 청크 크기 관리  
- **테스트 코드**(`tests/test_buffer_optimizer.py`) 작성  
- 기존 19개 시나리오 유지 및 형식 개선  
- 빈 버퍼, 단일 Write/Erase, 연속 Erase 병합, Erase 후 Write 보존 등 엣지 케이스 20~24번 추가  
- 각 …
=> [feat] Add SimpleBufferOptimizer and tests

README.md, command_core/shell_commands/help_command.py, command_core/shell_commands/testscenario.py
<details>
- `fix`: 버그 수정
</details>
---
- help 명령어 입력 시 명령어 사용방법 추가
- readme 현행화
- testscenario4 comment 수정
---
---
---
=> [refactor] comment 및 readme 정보 수정

ssd_core/buffer.py, ssd_core/buffer_optimizer_provider.py, tests/test_buffer.py
- 상황에 따라 Buffer 최적화 알고리즘을 변경하여 사용(=전략 패턴)할 수 있도록 `BufferOptimizerProvider` 클래스 추가
- `Buffer.insert()`에서 optimizer를 생성 후 최적화하도록 적용
---
---
- 
---
-
=> [feat] `Buffer` 객체에서 최적화 클래스를 호출하여 사용하도록 적용

command_core/shell_commands/runner.py, shell.py, validator.py
<details>
- `fix`: 버그 수정
</details>
---
- ssd erase시 erase의 size validator 검증
- 터미널에서 직접 호출시 동작하도록 코드 수정
- 러너에서 시나리오 통과 후 터미널 창에 로그 업데이트 되는 이슈 수정
---
---
---
=> [fix] erase validator 및 runner bug fix

shell.py, ssd_core/command_buffer.py, ssd_core/optimizer/discovery_buffer_optimizer.py, ssd_core/optimizer/simple_buffer_optimizer.py, tests/test_discovery_buffer_optimizer.py, tests/test_simple_buffer_optimizer.py, validator.py
[refactor] Packet Naming 변경
<details>
[refactor] Packet Naming 변경
- `test`: 테스트 코드 모두 통과하였습니다.
</details>
---
[refactor] Packet Naming 변경
{COMMAND} {ADDR} {VALUE} 에서 {COMMAND} {OP1} {OP2}로 변경했습니다.
---
---
---
=> [refactor] Packet Naming 변경

ssd_core/command_buffer.py, tests/test_runner.py, tests/test_shell_flush.py
[fix] Buffer에 Erase시 16진수 생성 내용 변경 및 test code Path 버그 수정
<details>
[fix] Buffer에 Erase시 16진수 생성 내용 변경 및 test code Path 버그 수정
</details>
---
[fix] Buffer에 Erase시 16진수 생성 내용 변경 및 test code Path 버그 수정했습니다!
기존 버퍼
W 0 0XFFFFFFFF
E 0 0X00000001
->
W 0 0xFFFFFFFF
E 0 1
---
---
---
=> [fix] Buffer에 Erase시 16진수 생성 내용 변경 및 test code Path 버그 수정
